Initial commit
IIExpanse/java-explore-with-me pull request #2
Opened 2023-01-12 14:51 UTC by Nagash40

2023-01-14 00:44 UTC, alexache requested changes

2023-01-14 00:44 UTC, alexache commented on ewm-service/pom.xml
> +                <version>1.1.3</version>
Версии зависимостей (и плагинов) должны быть указаны в родительском модуле

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/category/controller/CategoryController.java
> +    public ResponseEntity<CategoryDto> addCategory(@RequestBody @Valid NewCategoryDto newCategoryDto) {
Для чего использовать ResponseEntity, где нет необходимости в этой гибкости? Для этих контроллеров сойдет возвращение объектов ДТО

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +        Optional<Category> categoryOptional = categoryRepository.findById(id);
Эти 7 строк можно заменить на Category category = categoryRepository.findById(id).orElseThrow(() -> new CategoryNotFoundExcveption(..)); без какой дибо потери функциональности

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/category/service/impl/CategoryServiceImpl.java
> +        } else if (categoryRepository.existsCategoryByName(categoryDto.getName())) {
Что если вызвать обновление категории с тем же именем?

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/compilation/service/impl/CompilationServiceImpl.java
> +                                requestService.getConfirmedRequestsCount(event.getId()),
Это запрос к базе в цикле (в мапе стрима), такого не должно быть. Нужен один запрос по списку событий, тоже и про обращения к сервису статистики

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/event/model/Event.java
> +    Set<ParticipationRequest> requests;
Не хватает модификатора доступа

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/event/repository/EventRepository.java
> +//    @Query(value = "SELECT e FROM Event e " +
Не должно оставаться закомментированного кода

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/event/service/impl/EventServiceImpl.java
> +                        requestService.getConfirmedRequestsCount(event.getId()),
запрос к базе в цикле

2023-01-14 00:44 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/stats/dto/ViewStats.java
> +    String app;
Не хватает модификаторов доступа

2023-01-14 18:56 UTC, Nagash40 commented
Привет, спасибо за ревью. Высылаю новую версию с учетом всех комментариев.
Из всех циклов убраны методы, обращающиеся к БД. На замену им реализованы методы, принимающие коллекции айдишников и формирующие мапы с необходимыми значениями.

2023-01-16 11:43 UTC, alexache approved these changes

2023-01-16 11:43 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/compilation/repository/impl/CompilationRepositoryImpl.java
> +public class CompilationRepositoryImpl implements CompilationRepositoryCustom {
(опционально) действительно ли есть необходимость в таком подходе с реализацией на jdbc? Разве добавление в список событий на модели и сохранение не решит этой проблемы?

2023-01-16 11:43 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/request/service/impl/RequestServiceImpl.java
> +        requestRepository.getAllEventIdsFromConfirmedRequests(ids, RequestStatus.CONFIRMED)
(опционально) мне кажется, есть способ проще через подсчет количества подтвержденных заявок по событиям. Так тоже работает, но немного больше работы по обработке данных после

2023-01-16 11:43 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/request/service/impl/RequestServiceImpl.java
> +                .forEach(id -> map.put(id, map.get(id) + 1));
(опционально) для такого рода изменений лучше подходит метод compute у мапы. Тогда и первоначальное наполнение нулями не потребуется

2023-01-16 11:43 UTC, alexache commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/stats/service/impl/EwmStatsServiceImpl.java
> +        eventIds.forEach(id -> map.put(id, 0));
Это операция кажется лишней

2023-01-16 11:43 UTC, alexache commented on stats-server/src/main/java/ru/yandex/practicum/stats/service/impl/StatsServiceImpl.java
> +                    hitsMap.put(uri, hitsMap.get(uri) + 1);
(опционально) Тут тоже лучше подойдёт compute использовать

2023-01-17 15:18 UTC, Nagash40 commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/compilation/repository/impl/CompilationRepositoryImpl.java
> +public class CompilationRepositoryImpl implements CompilationRepositoryCustom {
В логике сервиса при добавлении подборки сейчас так и делается - внутрь кладется список событий, но это ни к чему не приводит. Как я [вычитал](https://stackoverflow.com/questions/36239030/manytomany-relation-not-save), это связано с тем, что связь ManyToMany в данном случае расписана в модели события (владельце связи). 
Насколько я понимаю, для корректной работы такого сохранения надо или сохранять подборку, а потом доставать модели событий и сохранять их с подборкой внутри, либо делать владельцем связи подборку, что наверно более правильно.
Вообще я скорее потом попробую композитный ключ реализовать, чтобы ассоциативная таблица была представлена в своем собственном классе и не было таких странностей.

2023-01-17 15:20 UTC, Nagash40 commented on ewm-service/src/main/java/ru/yandex/practicum/ewm/request/service/impl/RequestServiceImpl.java
> +        requestRepository.getAllEventIdsFromConfirmedRequests(ids, RequestStatus.CONFIRMED)
Не очень понял этот момент. Если выгружать список событий, а потом в них смотреть заявки, получится более объемно, чем простая выгрузка айдишников, как сейчас

2023-01-17 15:28 UTC, Nagash40 commented
Спасибо за ревью и подсказку с compute, скорректирую это и буду сливать.

2023-01-17 18:30 UTC, merged